### ISSUE TITLE
Tests on MoobX-0.1.0 have started to fail

### ISSUE THREAD

**Issue by andk** [yanick/MoobX#7]
Sample fail report: http://www.cpantesters.org/cpan/report/6970a31c-4438-11ed-bc55-70a14c555302

Regression analysis on my smokers tells:

``` text
****************************************************************
Regression 'mod:Exporter::Tiny'
****************************************************************
Name                   Theta          StdErr     T-stat
[0='const']           1.0000          0.0000    21247741018179344.00
[1='eq_1.000000']             0.0000          0.0000       0.20
[2='eq_1.002001']            -0.0000          0.0000      -2.47
[3='eq_1.002002']            -0.0000          0.0000      -0.22
[4='eq_1.004000']             0.0000          0.0000       0.61
[5='eq_1.004002']             0.0000          0.0000       1.37
[6='eq_1.004003']            -1.0000          0.0000    -5486143140529132.00

R^2= 1.000, N= 161, K= 7
****************************************************************
```

which can be read as: likely cause Exporter-Tiny-1.004003 . @tobyink, can you take a look?

**Comment by tobyink** [comment]
Before 1.004003, negated tags, for example:

```perl
use Your::Module '!:sometag';
```

were a no-op. They were documented as working, but didn't!

`_exporter_expand_tag` is called to translate a tag name like `:sometag` to a list of subnames. Now that negated tags are implemented, it is also called for the negation of the tag. `_exporter_expand_tag` is not given any indication of the context it's being called in — it doesn't know whether the caller requested the tag or the negated tag.

This means that previously, when you called:

```perl
use MoobX '!:attributes';
```

... the `!:attributes` was doing nothing. However it worked because having explicit arguments in the import list suppresses importing the default arguments (`@EXPORT`).

Now the line calls `_exporter_expand_tag` which you've overridden to set up attributes for the caller.

I do think it would be useful for `_exporter_expand_tag` to be given some context about whether it's being called for a negated tag or not. However, in the mean time, I do have a workaround for you.

**Comment by tobyink** [comment]
For reference, here's a [related Exporter::Tiny issue](https://github.com/tobyink/p5-exporter-tiny/issues/8). The fix to that issue, resulted in this MoobX issue.

**Comment by yanick** [comment]
Thanks! You be awesome! :-)

**Comment by yanick** [comment]
Change merged and new release punted to CPAN. Thanks!
